# Generated by Django 4.1.2 on 2022-10-30 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_weeks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workweek',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 0, 8, 39, 841092, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workweek',
            name='work_day',
            field=models.CharField(blank=True, choices=[('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=30, null=True),
        ),
    ]
