# Generated by Django 4.1.2 on 2022-11-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0004_remove_bottle_end_count_remove_bottle_start_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_weeks', '0005_alter_workweek_period_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workweek',
            name='work_day',
        ),
        migrations.CreateModel(
            name='WorkWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(blank=True, choices=[('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=30, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bottles.bottleinventory')),
                ('work_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_weeks.workweek')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
