# Generated by Django 4.1.2 on 2022-11-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_weeks', '0006_remove_workweek_work_day_workweekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workweekday',
            name='inventory',
        ),
    ]
