# Generated by Django 4.1.2 on 2022-11-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0005_delete_bottleinventory'),
        ('work_weeks', '0007_remove_workweekday_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workweekday',
            name='bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bottles.bottle'),
        ),
        migrations.AddField(
            model_name='workweekday',
            name='end_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workweekday',
            name='start_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
