# Generated by Django 4.1.2 on 2022-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0002_bottle_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='end_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='updated_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
