# Generated by Django 4.1.2 on 2022-11-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_weeks', '0007_remove_workweekday_inventory'),
        ('bottles', '0004_remove_bottle_end_count_remove_bottle_start_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BottleInventory',
        ),
    ]
